try{
var aa="activate",q="function",r="object",ba="unhandledrejection";function v(){return function(){}}function ca(a){return function(){return a}}
var x,da=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}},y=function(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):{next:da(a)}},ea=typeof Object.defineProperties==q?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a},fa=function(a){a=[r==typeof globalThis&&globalThis,a,r==typeof window&&window,r==typeof self&&self,r==typeof global&&global];for(var b=
0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("a");},B=fa(this),C=function(a,b){if(b)a:{var c=B;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];if(!(e in c))break a;c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&ea(c,a,{configurable:!0,writable:!0,value:b})}};
C("Symbol",function(a){if(a)return a;var b=function(f,l){this.g=f;ea(this,"description",{configurable:!0,writable:!0,value:l})};b.prototype.toString=function(){return this.g};var c="jscomp_symbol_"+(1E9*Math.random()>>>0)+"_",d=0,e=function(f){if(this instanceof e)throw new TypeError("b");return new b(c+(f||"")+"_"+d++,f)};return e});
C("Symbol.iterator",function(a){if(a)return a;a=Symbol("c");for(var b="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),c=0;c<b.length;c++){var d=B[b[c]];typeof d===q&&typeof d.prototype[a]!=q&&ea(d.prototype,a,{configurable:!0,writable:!0,value:function(){return ha(da(this))}})}return a});var ha=function(a){a={next:a};a[Symbol.iterator]=function(){return this};return a};
C("Promise",function(a){function b(){this.g=null}function c(l){return l instanceof e?l:new e(function(k){k(l)})}if(a)return a;b.prototype.h=function(l){if(null==this.g){this.g=[];var k=this;this.i(function(){k.l()})}this.g.push(l)};var d=B.setTimeout;b.prototype.i=function(l){d(l,0)};b.prototype.l=function(){for(;this.g&&this.g.length;){var l=this.g;this.g=[];for(var k=0;k<l.length;++k){var m=l[k];l[k]=null;try{m()}catch(n){this.j(n)}}}this.g=null};b.prototype.j=function(l){this.i(function(){throw l;
})};var e=function(l){this.g=0;this.i=void 0;this.h=[];this.o=!1;var k=this.j();try{l(k.resolve,k.reject)}catch(m){k.reject(m)}};e.prototype.j=function(){function l(n){return function(p){m||(m=!0,n.call(k,p))}}var k=this,m=!1;return{resolve:l(this.G),reject:l(this.l)}};e.prototype.G=function(l){if(l===this)this.l(new TypeError("d"));else if(l instanceof e)this.P(l);else{a:switch(typeof l){case r:var k=null!=l;break a;case q:k=!0;break a;default:k=!1}k?this.F(l):this.m(l)}};e.prototype.F=function(l){var k=
void 0;try{k=l.then}catch(m){this.l(m);return}typeof k==q?this.ma(k,l):this.m(l)};e.prototype.l=function(l){this.s(2,l)};e.prototype.m=function(l){this.s(1,l)};e.prototype.s=function(l,k){if(0!=this.g)throw Error("e`"+l+"`"+k+"`"+this.g);this.g=l;this.i=k;2===this.g&&this.H();this.C()};e.prototype.H=function(){var l=this;d(function(){if(l.D()){var k=B.console;"undefined"!==typeof k&&k.error(l.i)}},1)};e.prototype.D=function(){if(this.o)return!1;var l=B.CustomEvent,k=B.Event,m=B.dispatchEvent;if("undefined"===
typeof m)return!0;typeof l===q?l=new l(ba,{cancelable:!0}):typeof k===q?l=new k(ba,{cancelable:!0}):(l=B.document.createEvent("CustomEvent"),l.initCustomEvent(ba,!1,!0,l));l.promise=this;l.reason=this.i;return m(l)};e.prototype.C=function(){if(null!=this.h){for(var l=0;l<this.h.length;++l)f.h(this.h[l]);this.h=null}};var f=new b;e.prototype.P=function(l){var k=this.j();l.L(k.resolve,k.reject)};e.prototype.ma=function(l,k){var m=this.j();try{l.call(k,m.resolve,m.reject)}catch(n){m.reject(n)}};e.prototype.then=
function(l,k){function m(t,u){return typeof t==q?function(z){try{n(t(z))}catch(A){p(A)}}:u}var n,p,w=new e(function(t,u){n=t;p=u});this.L(m(l,n),m(k,p));return w};e.prototype.catch=function(l){return this.then(void 0,l)};e.prototype.L=function(l,k){function m(){switch(n.g){case 1:l(n.i);break;case 2:k(n.i);break;default:throw Error("f`"+n.g);}}var n=this;null==this.h?f.h(m):this.h.push(m);this.o=!0};e.resolve=c;e.reject=function(l){return new e(function(k,m){m(l)})};e.race=function(l){return new e(function(k,
m){for(var n=y(l),p=n.next();!p.done;p=n.next())c(p.value).L(k,m)})};e.all=function(l){var k=y(l),m=k.next();return m.done?c([]):new e(function(n,p){function w(z){return function(A){t[z]=A;u--;0==u&&n(t)}}var t=[],u=0;do t.push(void 0),u++,c(m.value).L(w(t.length-1),p),m=k.next();while(!m.done)})};return e});var ia=function(a,b,c){if(null==a)throw new TypeError("g`"+c);if(b instanceof RegExp)throw new TypeError("h`"+c);return a+""};
C("String.prototype.startsWith",function(a){return a?a:function(b,c){var d=ia(this,b,"startsWith"),e=d.length,f=b.length;c=Math.max(0,Math.min(c|0,d.length));for(var l=0;l<f&&c<e;)if(d[c++]!=b[l++])return!1;return l>=f}});var D=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};
C("WeakMap",function(a){function b(){}function c(m){var n=typeof m;return n===r&&null!==m||n===q}function d(m){if(!D(m,f)){var n=new b;ea(m,f,{value:n})}}function e(m){var n=Object[m];n&&(Object[m]=function(p){if(p instanceof b)return p;Object.isExtensible(p)&&d(p);return n(p)})}if(function(){if(!a||!Object.seal)return!1;try{var m=Object.seal({}),n=Object.seal({}),p=new a([[m,2],[n,3]]);if(2!=p.get(m)||3!=p.get(n))return!1;p.delete(m);p.set(n,4);return!p.has(m)&&4==p.get(n)}catch(w){return!1}}())return a;
var f="$jscomp_hidden_"+Math.random();e("freeze");e("preventExtensions");e("seal");var l=0,k=function(m){this.g=(l+=Math.random()+1).toString();if(m){m=y(m);for(var n;!(n=m.next()).done;)n=n.value,this.set(n[0],n[1])}};k.prototype.set=function(m,n){if(!c(m))throw Error("i");d(m);if(!D(m,f))throw Error("j`"+m);m[f][this.g]=n;return this};k.prototype.get=function(m){return c(m)&&D(m,f)?m[f][this.g]:void 0};k.prototype.has=function(m){return c(m)&&D(m,f)&&D(m[f],this.g)};k.prototype.delete=function(m){return c(m)&&
D(m,f)&&D(m[f],this.g)?delete m[f][this.g]:!1};return k});
C("Map",function(a){if(function(){if(!a||typeof a!=q||!a.prototype.entries||typeof Object.seal!=q)return!1;try{var k=Object.seal({x:4}),m=new a(y([[k,"s"]]));if("s"!=m.get(k)||1!=m.size||m.get({x:4})||m.set({x:4},"t")!=m||2!=m.size)return!1;var n=m.entries(),p=n.next();if(p.done||p.value[0]!=k||"s"!=p.value[1])return!1;p=n.next();return p.done||4!=p.value[0].x||"t"!=p.value[1]||!n.next().done?!1:!0}catch(w){return!1}}())return a;var b=new WeakMap,c=function(k){this.h={};this.g=f();this.size=0;if(k){k=
y(k);for(var m;!(m=k.next()).done;)m=m.value,this.set(m[0],m[1])}};c.prototype.set=function(k,m){k=0===k?0:k;var n=d(this,k);n.list||(n.list=this.h[n.id]=[]);n.u?n.u.value=m:(n.u={next:this.g,B:this.g.B,head:this.g,key:k,value:m},n.list.push(n.u),this.g.B.next=n.u,this.g.B=n.u,this.size++);return this};c.prototype.delete=function(k){k=d(this,k);return k.u&&k.list?(k.list.splice(k.index,1),k.list.length||delete this.h[k.id],k.u.B.next=k.u.next,k.u.next.B=k.u.B,k.u.head=null,this.size--,!0):!1};c.prototype.clear=
function(){this.h={};this.g=this.g.B=f();this.size=0};c.prototype.has=function(k){return!!d(this,k).u};c.prototype.get=function(k){return(k=d(this,k).u)&&k.value};c.prototype.entries=function(){return e(this,function(k){return[k.key,k.value]})};c.prototype.keys=function(){return e(this,function(k){return k.key})};c.prototype.values=function(){return e(this,function(k){return k.value})};c.prototype.forEach=function(k,m){for(var n=this.entries(),p;!(p=n.next()).done;)p=p.value,k.call(m,p[1],p[0],this)};
c.prototype[Symbol.iterator]=c.prototype.entries;var d=function(k,m){var n=m&&typeof m;n==r||n==q?b.has(m)?n=b.get(m):(n=""+ ++l,b.set(m,n)):n="p_"+m;var p=k.h[n];if(p&&D(k.h,n))for(k=0;k<p.length;k++){var w=p[k];if(m!==m&&w.key!==w.key||m===w.key)return{id:n,list:p,index:k,u:w}}return{id:n,list:p,index:-1,u:void 0}},e=function(k,m){var n=k.g;return ha(function(){if(n){for(;n.head!=k.g;)n=n.B;for(;n.next!=n.head;)return n=n.next,{done:!1,value:m(n)};n=null}return{done:!0,value:void 0}})},f=function(){var k=
{};return k.B=k.next=k.head=k},l=0;return c});C("Array.prototype.find",function(a){return a?a:function(b,c){a:{var d=this;d instanceof String&&(d=String(d));for(var e=d.length,f=0;f<e;f++){var l=d[f];if(b.call(c,l,f,d)){b=l;break a}}b=void 0}return b}});C("String.prototype.endsWith",function(a){return a?a:function(b,c){var d=ia(this,b,"endsWith");void 0===c&&(c=d.length);c=Math.max(0,Math.min(c|0,d.length));for(var e=b.length;0<e&&0<c;)if(d[--c]!=b[--e])return!1;return 0>=e}});
var ja=function(a,b){a instanceof String&&(a+="");var c=0,d=!1,e={next:function(){if(!d&&c<a.length){var f=c++;return{value:b(f,a[f]),done:!1}}d=!0;return{done:!0,value:void 0}}};e[Symbol.iterator]=function(){return e};return e};C("Array.prototype.keys",function(a){return a?a:function(){return ja(this,function(b){return b})}});
C("Set",function(a){if(function(){if(!a||typeof a!=q||!a.prototype.entries||typeof Object.seal!=q)return!1;try{var c=Object.seal({x:4}),d=new a(y([c]));if(!d.has(c)||1!=d.size||d.add(c)!=d||1!=d.size||d.add({x:4})!=d||2!=d.size)return!1;var e=d.entries(),f=e.next();if(f.done||f.value[0]!=c||f.value[1]!=c)return!1;f=e.next();return f.done||f.value[0]==c||4!=f.value[0].x||f.value[1]!=f.value[0]?!1:e.next().done}catch(l){return!1}}())return a;var b=function(c){this.g=new Map;if(c){c=y(c);for(var d;!(d=
c.next()).done;)this.add(d.value)}this.size=this.g.size};b.prototype.add=function(c){c=0===c?0:c;this.g.set(c,c);this.size=this.g.size;return this};b.prototype.delete=function(c){c=this.g.delete(c);this.size=this.g.size;return c};b.prototype.clear=function(){this.g.clear();this.size=0};b.prototype.has=function(c){return this.g.has(c)};b.prototype.entries=function(){return this.g.entries()};b.prototype.values=function(){return this.g.values()};b.prototype.keys=b.prototype.values;b.prototype[Symbol.iterator]=
b.prototype.values;b.prototype.forEach=function(c,d){var e=this;this.g.forEach(function(f){return c.call(d,f,f,e)})};return b});C("Array.prototype.values",function(a){return a?a:function(){return ja(this,function(b,c){return c})}});
C("Array.from",function(a){return a?a:function(b,c,d){c=null!=c?c:function(k){return k};var e=[],f="undefined"!=typeof Symbol&&Symbol.iterator&&b[Symbol.iterator];if(typeof f==q){b=f.call(b);for(var l=0;!(f=b.next()).done;)e.push(c.call(d,f.value,l++))}else for(f=b.length,l=0;l<f;l++)e.push(c.call(d,b[l],l));return e}});C("Object.is",function(a){return a?a:function(b,c){return b===c?0!==b||1/b===1/c:b!==b&&c!==c}});
C("Array.prototype.includes",function(a){return a?a:function(b,c){var d=this;d instanceof String&&(d=String(d));var e=d.length;c=c||0;for(0>c&&(c=Math.max(c+e,0));c<e;c++){var f=d[c];if(f===b||Object.is(f,b))return!0}return!1}});C("String.prototype.includes",function(a){return a?a:function(b,c){return-1!==ia(this,b,"includes").indexOf(b,c||0)}});
C("Promise.prototype.finally",function(a){return a?a:function(b){return this.then(function(c){return Promise.resolve(b()).then(function(){return c})},function(c){return Promise.resolve(b()).then(function(){throw c;})})}});
/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var E=this||self,ka="closure_uid_"+(1E9*Math.random()>>>0);

}catch(e){_DumpException(e)}
try{
var la=" for range <all>",ma=" with key ",na="Cache-Control",oa="ConstraintError",pa="Content-Disposition",ra="InvalidAccessError",sa="InvalidStateError",ta="QuotaExceededError",ua="TransactionInactiveError",va="UnknownError",wa="X-Content-Type-Options",xa="X-Gmail-SW-Cache-Control",ya="X-Gmail-SW-Cache-Warming-Request",za="abort",Aa="complete",Ba="cssModules",Ca="dispatcher_command",F="error",Da="gssmodulesetproto",Ea="match_bad_headers",Fa="modules",Ga="no_match_no_cache",Ha="number",Ia="readwrite",
Ja="removing from ",G="string",Ka="versions",H=function(a,b){if(Error.captureStackTrace)Error.captureStackTrace(this,H);else{var c=Error().stack;c&&(this.stack=c)}a&&(this.message=String(a));void 0!==b&&(this.cause=b)},La=function(){var a=E.navigator;return a&&(a=a.userAgent)?a:""},I=function(a){return-1!=La().indexOf(a)},Na=function(a){var b=Ma,c;for(c in b)a.call(void 0,b[c],c,b)},Pa=function(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var f=0;f<Oa.length;f++)c=
Oa[f],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}},Qa=v(),Ra=function(a){E.setTimeout(function(){throw a;},0)},Ta=function(a,b){return new Promise(function(c,d){Sa(a,F,d);Sa(a,Aa,function(){return c(b)})})},Wa=function(){return Ua(function(a){return a.startsWith("sw-")}).then(function(a){Va("ALL","quota_exceeded",!0);return a})},Ua=function(a){if(E.caches){var b=new Xa;return E.caches.keys().then(function(c){var d=c.filter(a).map(function(e){Ya(b,e);return E.caches.delete(e)});return Promise.all(d).then(function(){return d.length})})}return Promise.resolve(0)},
Va=function(a,b,c){var d=new Date,e=new Za({O:$a,parse:ab,ia:bb});return c&&"ALL"==a?cb(e).then(function(){return db(e,a,function(){return new eb(a,c,b,d)})}):db(e,a,function(){return new eb(a,c,b,d)})},fb=function(a,b){return(a=/^\/_\/scs\/mail-static(?:-\w+)?\/_\/([sj]s)(?=\/).*\/k=([^\/]*)/.exec(a.pathname))?{name:"sw-"+b+"-"+a[1]+"-"+a[2],type:a[1]}:null},gb=function(a){return!!fb(a,"noscope")},hb=function(a,b){return a.pathname==b&&!!a.searchParams&&!a.searchParams.get("ui")&&!a.searchParams.get("view")&&
null==a.searchParams.get("logout")},ob=function(a){var b=new URL(a.toString()),c;if(c=!ib.test(a.g))c=a.g,c=!(jb.test(c)||kb.test(c)||lb.test(c));if(c&&!mb(b))return!1;b=a.h;J(b);a=Array.from(b.g.values());b=Array.from(b.g.keys());c=[];for(var d=0;d<b.length;d++)for(var e=a[d],f=0;f<e.length;f++)c.push(b[d]);a=y(c);for(b=a.next();!b.done;b=a.next())if(!nb.has(b.value))return!1;return!0},pb=function(a){a=new URL(a);var b=a.searchParams;return a.origin+a.pathname+(b.toString()?"?"+b.toString():"")},
tb=function(a){a=pb(a);a=qb(a);if(ob(a))for(var b=a.h,c=y(rb),d=c.next();!d.done;d=c.next())sb(b,d.value);return pb(a.toString())},mb=function(a){a=a.pathname;return ub.test(a)||vb.test(a)},wb=function(a){return 1E3*(typeof a===Ha?a:0)},xb=function(a,b,c){var d=new Map;if(b=b.headers.get(na)){b=y(b.split(","));for(var e=b.next();!e.done;e=b.next())if(e=e.value.trim().split("="),1<e.length){var f=e[1];isFinite(f)&&(f=String(f));(f=typeof f===G?/^\s*-?0x/i.test(f)?parseInt(f,16):parseInt(f,10):NaN)&&
d.set(e[0],f)}else d.set(e[0],!0)}if(d.has("no-store")||d.has("no-cache"))return!1;if((b=d.get("max-stale"))&&"boolean"===typeof b)return!0;e=Date.parse(c.headers.get("Date"))||0;a-=e;e=wb(d.get("min-fresh"));if(!(d=wb(d.get("max-age"))))a:{if(d=c.headers.get(na)){if((f=d.match(/[,\s]*s-maxage=(\d+)[,\s]*/))&&1<f.length){d=1E3*Number(f[1]);break a}if((d=d.match(/[,\s]*max-age=(\d+)[,\s]*/))&&1<d.length){d=1E3*Number(d[1]);break a}}d=Date.parse(c.headers.get("Expires"));c=Date.parse(c.headers.get("Date"));
d=d&&c?d-c:0}return a+e<d+wb(b)},yb=function(a){if(!a.headers.get(xa))return!1;a=Date.parse(a.headers.get("Date"));return!isNaN(a)&&a+12096E5>Date.now()},zb=function(a){var b=a.target.result;switch(a.oldVersion){case 0:b.createObjectStore(Ka),b.createObjectStore(Fa);case 1:b.createObjectStore(Ba)}},Ab=function(a){return new Promise(function(b,c){a.onsuccess=function(){return b(a.result)};a.onerror=function(){return c(a.error)}})},Bb=function(a){return new Promise(function(b,c){a.oncomplete=function(){return b()};
a.onerror=function(){return c(a.error)}})},Cb=function(a){return"k="+K(a,"k")+"/ck="+(K(a,"ck")||"")+"/am="+(K(a,"am")||"")},L=function(a){if(!Db){if("undefined"===typeof TextEncoder)throw Error("s");Db=new TextEncoder}return Db.encode(a)},Eb=function(a){return a?L(a):null},Hb=function(a,b,c){return c?b.reduce(function(d,e){var f=a.get(e);if(e===c){e=b.reduce(function(l,k){k!==c&&l.push("'"+k+"'");return l},[]).join(",");if(!Fb){if("undefined"===typeof TextDecoder)throw Error("t");Fb=new TextDecoder}f=
Fb.decode(f).replace(Gb,"$1"+e+"$2");d.push(L(f))}else d.push(f);return d},[]):b.map(function(d){return a.get(d)})},Mb=function(a,b){return"1"==K(a,"ed")&&b?new Set(Ib(Jb(a).concat(Kb(a)),b,Lb(a))):new Set(Jb(a).concat(Kb(a)))},Ib=function(a,b,c){var d=[],e=new Set;a=y(a);for(var f=a.next();!f.done;f=a.next())if(1!==Nb(f.value,b,c,new Set,e,d))return null;return d},Nb=function(a,b,c,d,e,f){if(e.has(a))return 1;if(d.has(a))return 2;d.add(a);if(b.has(a))for(var l=y(b.get(a)),k=l.next();!k.done;k=l.next())if(k=
Nb(k.value,b,c,d,e,f),1!==k)return k;if(c.hasOwnProperty(a))for(l=y(Object.keys(c[a])),k=l.next();!k.done;k=l.next())if(k=Nb(k.value,b,c,d,e,f),1!==k)return k;f.push(a);e.add(a);return 1},M=function(a){if(!(a instanceof Array)){a=y(a);for(var b,c=[];!(b=a.next()).done;)c.push(b.value);a=c}return a},N=function(a){var b=typeof a;return b==r&&null!=a||b==q},Ob=0,Pb=function(a){null!==a&&"removeAttribute"in a&&a.removeAttribute(ka);try{delete a[ka]}catch(b){}},Qb=function(a,b,c){return a.call.apply(a.bind,
arguments)},Rb=function(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var e=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(e,d);return a.apply(b,e)}}return function(){return a.apply(b,arguments)}},O=function(a,b,c){Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?O=Qb:O=Rb;return O.apply(null,arguments)},P=function(a,b){function c(){}c.prototype=b.prototype;a.ja=b.prototype;
a.prototype=new c;a.prototype.constructor=a;a.Ya=function(d,e,f){for(var l=Array(arguments.length-2),k=2;k<arguments.length;k++)l[k-2]=arguments[k];return b.prototype[e].apply(d,l)}};
/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
P(H,Error);H.prototype.name="CustomError";
var Sb,Wb=function(a,b,c){if(typeof a===Ha)var d={name:Tb(a)};else d=a,a=Vb(a.name);this.code=a;this.g=d;b="Error "+b+": "+(this.g.name||"");c&&(b+=", "+c);H.call(this,b)};P(Wb,H);
var Q={ra:1,Oa:2,NOT_FOUND_ERR:3,ka:4,la:5,Pa:6,qa:7,ABORT_ERR:8,pa:9,Wa:10,TIMEOUT_ERR:11,oa:12,INVALID_ACCESS_ERR:13,INVALID_STATE_ERR:14},Xb=(E.g||E.h||Q).ra,Yb=(E.g||E.h||Q).NOT_FOUND_ERR,Zb=(E.g||E.h||Q).ka,$b=(E.g||E.h||Q).la,ac=(E.g||E.h||Q).qa,bc=(E.g||E.h||Q).ABORT_ERR,cc=(E.g||E.h||Q).pa,dc=(E.g||E.h||Q).TIMEOUT_ERR,ec=(E.g||E.h||Q).oa,fc=(E.DOMException||Q).INVALID_ACCESS_ERR,gc=(E.DOMException||Q).INVALID_STATE_ERR,Vb=function(a){switch(a){case va:return Xb;case "NotFoundError":return Yb;
case oa:return Zb;case "DataError":return $b;case ua:return ac;case "AbortError":return bc;case "ReadOnlyError":return cc;case "TimeoutError":return dc;case ta:return ec;case ra:return fc;case sa:return gc;default:return Xb}},Tb=function(a){switch(a){case Xb:return va;case Yb:return"NotFoundError";case Zb:return oa;case $b:return"DataError";case ac:return ua;case bc:return"AbortError";case cc:return"ReadOnlyError";case dc:return"TimeoutError";case ec:return ta;case fc:return ra;case gc:return sa;
default:return va}},hc=function(a,b){return F in a?new Wb(a.error,b):new Wb({name:va},b)},R=function(a,b){return"name"in a?new Wb(a,b+": "+a.message):new Wb({name:va},b)};
var ic=Array.prototype.indexOf?function(a,b){return Array.prototype.indexOf.call(a,b,void 0)}:function(a,b){if(typeof a===G)return typeof b!==G||1!=b.length?-1:a.indexOf(b,0);for(var c=0;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},jc=Array.prototype.some?function(a,b){return Array.prototype.some.call(a,b,void 0)}:function(a,b){for(var c=a.length,d=typeof a===G?a.split(""):a,e=0;e<c;e++)if(e in d&&b.call(void 0,d[e],e,a))return!0;return!1};
var S=function(a){var b=[],c=[],d={},e=function(f,l){var k=l+"  ";try{if(void 0===f)b.push("undefined");else if(null===f)b.push("NULL");else if(typeof f===G)b.push('"'+f.replace(/\n/g,"\n"+l)+'"');else if(typeof f===q)b.push(String(f).replace(/\n/g,"\n"+l));else if(N(f)){f[ka]||c.push(f);var m=Object.prototype.hasOwnProperty.call(f,ka)&&f[ka]||(f[ka]=++Ob);if(d[m])b.push("*** reference loop detected (id="+m+") ***");else{d[m]=!0;b.push("{");for(var n in f)typeof f[n]!==q&&(b.push("\n"),b.push(k),
b.push(n+" = "),e(f[n],k));b.push("\n"+l+"}");delete d[m]}}else b.push(f)}catch(p){b.push("*** "+p+" ***")}};e(a,"");for(a=0;a<c.length;a++)Pb(c[a]);return b.join("")};
var kc=v();
var T=function(a,b){this.type=a;this.g=this.target=b;this.defaultPrevented=!1};T.prototype.h=function(){this.defaultPrevented=!0};
var lc=function(){if(!E.addEventListener||!Object.defineProperty)return!1;var a=!1,b=Object.defineProperty({},"passive",{get:function(){a=!0}});try{E.addEventListener("test",v(),b),E.removeEventListener("test",v(),b)}catch(c){}return a}();
var mc=function(a){mc[" "](a);return a};mc[" "]=v();
var nc=I("Gecko")&&!(-1!=La().toLowerCase().indexOf("webkit")&&!I("Edge"))&&!(I("Trident")||I("MSIE"))&&!I("Edge");
var pc=function(a,b){T.call(this,a?a.type:"");this.relatedTarget=this.g=this.target=null;this.button=this.screenY=this.screenX=this.clientY=this.clientX=0;this.key="";this.metaKey=this.shiftKey=this.altKey=this.ctrlKey=!1;this.state=null;this.pointerId=0;this.pointerType="";this.i=null;if(a){var c=this.type=a.type,d=a.changedTouches&&a.changedTouches.length?a.changedTouches[0]:null;this.target=a.target||a.srcElement;this.g=b;if(b=a.relatedTarget){if(nc){a:{try{mc(b.nodeName);var e=!0;break a}catch(f){}e=
!1}e||(b=null)}}else"mouseover"==c?b=a.fromElement:"mouseout"==c&&(b=a.toElement);this.relatedTarget=b;d?(this.clientX=void 0!==d.clientX?d.clientX:d.pageX,this.clientY=void 0!==d.clientY?d.clientY:d.pageY,this.screenX=d.screenX||0,this.screenY=d.screenY||0):(this.clientX=void 0!==a.clientX?a.clientX:a.pageX,this.clientY=void 0!==a.clientY?a.clientY:a.pageY,this.screenX=a.screenX||0,this.screenY=a.screenY||0);this.button=a.button;this.key=a.key||"";this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=
a.shiftKey;this.metaKey=a.metaKey;this.pointerId=a.pointerId||0;this.pointerType=typeof a.pointerType===G?a.pointerType:oc[a.pointerType]||"";this.state=a.state;this.i=a;a.defaultPrevented&&pc.ja.h.call(this)}};P(pc,T);var oc={2:"touch",3:"pen",4:"mouse"};pc.prototype.h=function(){pc.ja.h.call(this);var a=this.i;a.preventDefault?a.preventDefault():a.returnValue=!1};
var qc="closure_listenable_"+(1E6*Math.random()|0),rc=function(a){return!(!a||!a[qc])};
var tc=0;
var uc=function(a,b,c,d,e){this.listener=a;this.proxy=null;this.src=b;this.type=c;this.capture=!!d;this.M=e;this.key=++tc;this.J=this.K=!1},vc=function(a){a.J=!0;a.listener=null;a.proxy=null;a.src=null;a.M=null};
var Oa="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");
var wc=function(a){this.src=a;this.g={};this.h=0};wc.prototype.add=function(a,b,c,d,e){var f=a.toString();a=this.g[f];a||(a=this.g[f]=[],this.h++);var l=xc(a,b,d,e);-1<l?(b=a[l],c||(b.K=!1)):(b=new uc(b,this.src,f,!!d,e),b.K=c,a.push(b));return b};var yc=function(a,b){var c=b.type;if(c in a.g){var d=a.g[c],e=ic(d,b),f;(f=0<=e)&&Array.prototype.splice.call(d,e,1);f&&(vc(b),0==a.g[c].length&&(delete a.g[c],a.h--))}};
wc.prototype.I=function(a,b,c,d){a=this.g[a.toString()];var e=-1;a&&(e=xc(a,b,c,d));return-1<e?a[e]:null};var xc=function(a,b,c,d){for(var e=0;e<a.length;++e){var f=a[e];if(!f.J&&f.listener==b&&f.capture==!!c&&f.M==d)return e}return-1};
var zc="closure_lm_"+(1E6*Math.random()|0),Ac={},Bc=0,Sa=function(a,b,c,d,e){if(d&&d.once)return Cc(a,b,c,d,e);if(Array.isArray(b)){for(var f=0;f<b.length;f++)Sa(a,b[f],c,d,e);return null}c=Dc(c);return rc(a)?a.A(b,c,N(d)?!!d.capture:!!d,e):Ec(a,b,c,!1,d,e)},Ec=function(a,b,c,d,e,f){if(!b)throw Error("k");var l=N(e)?!!e.capture:!!e,k=Fc(a);k||(a[zc]=k=new wc(a));c=k.add(b,c,d,l,f);if(c.proxy)return c;d=Gc();c.proxy=d;d.src=a;d.listener=c;if(a.addEventListener)lc||(e=l),void 0===e&&(e=!1),a.addEventListener(b.toString(),
d,e);else if(a.attachEvent)a.attachEvent(Hc(b.toString()),d);else if(a.addListener&&a.removeListener)a.addListener(d);else throw Error("l");Bc++;return c},Gc=function(){var a=Ic,b=function(c){return a.call(b.src,b.listener,c)};return b},Cc=function(a,b,c,d,e){if(Array.isArray(b)){for(var f=0;f<b.length;f++)Cc(a,b[f],c,d,e);return null}c=Dc(c);return rc(a)?a.fa(b,c,N(d)?!!d.capture:!!d,e):Ec(a,b,c,!0,d,e)},Jc=function(a,b,c,d,e){if(Array.isArray(b))for(var f=0;f<b.length;f++)Jc(a,b[f],c,d,e);else d=
N(d)?!!d.capture:!!d,c=Dc(c),rc(a)?a.T(b,c,d,e):a&&(a=Fc(a))&&(b=a.I(b,c,d,e))&&Kc(b)},Kc=function(a){if(typeof a!==Ha&&a&&!a.J){var b=a.src;if(rc(b))yc(b.h,a);else{var c=a.type,d=a.proxy;b.removeEventListener?b.removeEventListener(c,d,a.capture):b.detachEvent?b.detachEvent(Hc(c),d):b.addListener&&b.removeListener&&b.removeListener(d);Bc--;(c=Fc(b))?(yc(c,a),0==c.h&&(c.src=null,b[zc]=null)):vc(a)}}},Hc=function(a){return a in Ac?Ac[a]:Ac[a]="on"+a},Ic=function(a,b){if(a.J)a=!0;else{b=new pc(b,this);
var c=a.listener,d=a.M||a.src;a.K&&Kc(a);a=c.call(d,b)}return a},Fc=function(a){a=a[zc];return a instanceof wc?a:null},Lc="__closure_events_fn_"+(1E9*Math.random()>>>0),Dc=function(a){if(typeof a===q)return a;a[Lc]||(a[Lc]=function(b){return a.handleEvent(b)});return a[Lc]};
var U=function(){this.h=new wc(this);this.m=this};P(U,kc);U.prototype[qc]=!0;x=U.prototype;x.addEventListener=function(a,b,c,d){Sa(this,a,b,c,d)};x.removeEventListener=function(a,b,c,d){Jc(this,a,b,c,d)};x.dispatchEvent=function(a){var b=this.m,c=a.type||a;if(typeof a===G)a=new T(a,b);else if(a instanceof T)a.target=a.target||b;else{var d=a;a=new T(c,b);Pa(a,d)}d=!0;b=a.g=b;d=Mc(b,c,!0,a)&&d;return d=Mc(b,c,!1,a)&&d};x.A=function(a,b,c,d){return this.h.add(String(a),b,!1,c,d)};
x.fa=function(a,b,c,d){return this.h.add(String(a),b,!0,c,d)};x.T=function(a,b,c,d){var e=this.h;a=String(a).toString();if(a in e.g){var f=e.g[a];b=xc(f,b,c,d);-1<b&&(vc(f[b]),Array.prototype.splice.call(f,b,1),0==f.length&&(delete e.g[a],e.h--))}};var Mc=function(a,b,c,d){b=a.h.g[String(b)];if(!b)return!0;b=b.concat();for(var e=!0,f=0;f<b.length;++f){var l=b[f];if(l&&!l.J&&l.capture==c){var k=l.listener,m=l.M||l.src;l.K&&yc(a.h,l);e=!1!==k.call(m,d)&&e}}return e&&!d.defaultPrevented};
U.prototype.I=function(a,b,c,d){return this.h.I(String(a),b,c,d)};
var Nc=function(a,b){this.i=a;this.j=b;this.h=0;this.g=null};Nc.prototype.get=function(){if(0<this.h){this.h--;var a=this.g;this.g=a.next;a.next=null}else a=this.i();return a};var Oc=function(a,b){a.j(b);100>a.h&&(a.h++,b.next=a.g,a.g=b)};
var Pc=v();
var Qc=function(){var a=document;var b="IFRAME";"application/xhtml+xml"===a.contentType&&(b=b.toLowerCase());return a.createElement(b)};
var Rc,Sc=function(){var a=E.MessageChannel;"undefined"===typeof a&&"undefined"!==typeof window&&window.postMessage&&window.addEventListener&&!I("Presto")&&(a=function(){var e=Qc();e.style.display="none";document.documentElement.appendChild(e);var f=e.contentWindow;e=f.document;e.open();e.close();var l="callImmediate"+Math.random(),k="file:"==f.location.protocol?"*":f.location.protocol+"//"+f.location.host;e=O(function(m){if(("*"==k||m.origin==k)&&m.data==l)this.port1.onmessage()},this);f.addEventListener("message",
e,!1);this.port1={};this.port2={postMessage:function(){f.postMessage(l,k)}}});if("undefined"!==typeof a&&!I("Trident")&&!I("MSIE")){var b=new a,c={},d=c;b.port1.onmessage=function(){if(void 0!==c.next){c=c.next;var e=c.X;c.X=null;e()}};return function(e){d.next={X:e};d=d.next;b.port2.postMessage(0)}}return function(e){E.setTimeout(e,0)}};
var Tc=function(){this.h=this.g=null};Tc.prototype.add=function(a,b){var c=Uc.get();c.set(a,b);this.h?this.h.next=c:this.g=c;this.h=c};var Wc=function(){var a=Vc,b=null;a.g&&(b=a.g,a.g=a.g.next,a.g||(a.h=null),b.next=null);return b},Uc=new Nc(function(){return new Xc},function(a){return a.reset()}),Xc=function(){this.next=this.scope=this.g=null};Xc.prototype.set=function(a,b){this.g=a;this.scope=b;this.next=null};Xc.prototype.reset=function(){this.next=this.scope=this.g=null};
var Yc,Zc=!1,Vc=new Tc,ad=function(a,b){Yc||$c();Zc||(Yc(),Zc=!0);Vc.add(a,b)},$c=function(){if(E.Promise&&E.Promise.resolve){var a=E.Promise.resolve(void 0);Yc=function(){a.then(bd)}}else Yc=function(){var b=bd;typeof E.setImmediate!==q||E.Window&&E.Window.prototype&&!I("Edge")&&E.Window.prototype.setImmediate==E.setImmediate?(Rc||(Rc=Sc()),Rc(b)):E.setImmediate(b)}},bd=function(){for(var a;a=Wc();){try{a.g.call(a.scope)}catch(b){Ra(b)}Oc(Uc,a)}Zc=!1};
var cd=function(a){if(!a)return!1;try{return!!a.$goog_Thenable}catch(b){return!1}};
var V=function(a){this.g=0;this.o=void 0;this.j=this.h=this.i=null;this.l=this.m=!1;if(a!=Pc)try{var b=this;a.call(void 0,function(c){dd(b,2,c)},function(c){dd(b,3,c)})}catch(c){dd(this,3,c)}},ed=function(){this.next=this.i=this.h=this.j=this.g=null;this.l=!1};ed.prototype.reset=function(){this.i=this.h=this.j=this.g=null;this.l=!1};var fd=new Nc(function(){return new ed},function(a){a.reset()}),gd=function(a,b,c){var d=fd.get();d.j=a;d.h=b;d.i=c;return d};
V.prototype.then=function(a,b,c){return hd(this,typeof a===q?a:null,typeof b===q?b:null,c)};V.prototype.$goog_Thenable=!0;V.prototype.cancel=function(a){if(0==this.g){var b=new id(a);ad(function(){jd(this,b)},this)}};
var jd=function(a,b){if(0==a.g)if(a.i){var c=a.i;if(c.h){for(var d=0,e=null,f=null,l=c.h;l&&(l.l||(d++,l.g==a&&(e=l),!(e&&1<d)));l=l.next)e||(f=l);e&&(0==c.g&&1==d?jd(c,b):(f?(d=f,d.next==c.j&&(c.j=d),d.next=d.next.next):kd(c),ld(c,e,3,b)))}a.i=null}else dd(a,3,b)},nd=function(a,b){a.h||2!=a.g&&3!=a.g||md(a);a.j?a.j.next=b:a.h=b;a.j=b},hd=function(a,b,c,d){var e=gd(null,null,null);e.g=new V(function(f,l){e.j=b?function(k){try{var m=b.call(d,k);f(m)}catch(n){l(n)}}:f;e.h=c?function(k){try{var m=c.call(d,
k);void 0===m&&k instanceof id?l(k):f(m)}catch(n){l(n)}}:l});e.g.i=a;nd(a,e);return e.g};V.prototype.C=function(a){this.g=0;dd(this,2,a)};V.prototype.D=function(a){this.g=0;dd(this,3,a)};
var dd=function(a,b,c){if(0==a.g){a===c&&(b=3,c=new TypeError("m"));a.g=1;a:{var d=c,e=a.C,f=a.D;if(d instanceof V){nd(d,gd(e||Pc,f||null,a));var l=!0}else if(cd(d))d.then(e,f,a),l=!0;else{if(N(d))try{var k=d.then;if(typeof k===q){od(d,k,e,f,a);l=!0;break a}}catch(m){f.call(a,m);l=!0;break a}l=!1}}l||(a.o=c,a.g=b,a.i=null,md(a),3!=b||c instanceof id||pd(a,c))}},od=function(a,b,c,d,e){var f=!1,l=function(m){f||(f=!0,c.call(e,m))},k=function(m){f||(f=!0,d.call(e,m))};try{b.call(a,l,k)}catch(m){k(m)}},
md=function(a){a.m||(a.m=!0,ad(a.s,a))},kd=function(a){var b=null;a.h&&(b=a.h,a.h=b.next,b.next=null);a.h||(a.j=null);return b};V.prototype.s=function(){for(var a;a=kd(this);)ld(this,a,this.g,this.o);this.m=!1};
var ld=function(a,b,c,d){if(3==c&&b.h&&!b.l)for(;a&&a.l;a=a.i)a.l=!1;if(b.g)b.g.i=null,qd(b,c,d);else try{b.l?b.j.call(b.i):qd(b,c,d)}catch(e){rd.call(null,e)}Oc(fd,b)},qd=function(a,b,c){2==b?a.j.call(a.i,c):a.h&&a.h.call(a.i,c)},pd=function(a,b){a.l=!0;ad(function(){a.l&&rd.call(null,b)})},rd=Ra,id=function(a){H.call(this,a)};P(id,H);id.prototype.name="cancel";
/*

 Copyright 2005, 2007 Bob Ippolito. All Rights Reserved.
 Copyright The Closure Library Authors.
 SPDX-License-Identifier: MIT
*/
var W=function(a,b){this.m=[];this.H=a;this.G=b||null;this.l=this.j=!1;this.i=void 0;this.D=this.P=this.s=!1;this.o=0;this.h=null;this.C=0};P(W,Qa);W.prototype.cancel=function(a){if(this.j)this.i instanceof W&&this.i.cancel();else{if(this.h){var b=this.h;delete this.h;a?b.cancel(a):(b.C--,0>=b.C&&b.cancel())}this.H?this.H.call(this.G,this):this.D=!0;this.j||X(this,new sd(this))}};W.prototype.F=function(a,b){this.s=!1;td(this,a,b)};
var td=function(a,b,c){a.j=!0;a.i=c;a.l=!b;ud(a)},wd=function(a){if(a.j){if(!a.D)throw new vd(a);a.D=!1}};W.prototype.g=function(a){wd(this);td(this,!0,a)};var X=function(a,b){wd(a);td(a,!1,b)},yd=function(a,b){return xd(a,b,null)},zd=function(a,b){return xd(a,null,b)},xd=function(a,b,c,d){a.m.push([b,c,d]);a.j&&ud(a);return a};W.prototype.then=function(a,b,c){var d,e,f=new V(function(l,k){e=l;d=k});xd(this,e,function(l){l instanceof sd?f.cancel():d(l);return Ad},this);return f.then(a,b,c)};
W.prototype.$goog_Thenable=!0;
var Bd=function(a){return jc(a.m,function(b){return typeof b[1]===q})},Ad={},ud=function(a){if(a.o&&a.j&&Bd(a)){var b=a.o,c=Cd[b];c&&(E.clearTimeout(c.g),delete Cd[b]);a.o=0}a.h&&(a.h.C--,delete a.h);b=a.i;for(var d=c=!1;a.m.length&&!a.s;){var e=a.m.shift(),f=e[0],l=e[1];e=e[2];if(f=a.l?l:f)try{var k=f.call(e||a.G,b);k===Ad&&(k=void 0);void 0!==k&&(a.l=a.l&&(k==b||k instanceof Error),a.i=b=k);if(cd(b)||typeof E.Promise===q&&b instanceof E.Promise)d=!0,a.s=!0}catch(m){b=m,a.l=!0,Bd(a)||(c=!0)}}a.i=
b;d&&(k=O(a.F,a,!0),d=O(a.F,a,!1),b instanceof W?(xd(b,k,d),b.P=!0):b.then(k,d));c&&(b=new Dd(b),Cd[b.g]=b,a.o=b.g)},vd=function(){H.call(this)};P(vd,H);vd.prototype.message="Deferred has already fired";vd.prototype.name="AlreadyCalledError";var sd=function(){H.call(this)};P(sd,H);sd.prototype.message="Deferred was canceled";sd.prototype.name="CanceledError";var Dd=function(a){this.g=E.setTimeout(O(this.i,this),0);this.h=a};Dd.prototype.i=function(){delete Cd[this.g];throw this.h;};var Cd={};
var Ed=function(a){this.g=a},Fd=function(a,b,c,d,e){var f=new W;try{var l=e?a.g[b](d,e):a.g[b](d)}catch(k){return c+=S(d),e&&(c+=", with key "+S(e)),X(f,R(k,c)),f}l.onsuccess=function(k){f.g(k.target.result)};l.onerror=function(k){c+=S(d);e&&(c+=", with key "+S(e));X(f,hc(k.target,c))};return f},Gd=function(a,b){return Fd(a,"put","putting into "+a.g.name+" with value",b)};Ed.prototype.add=function(a,b){return Fd(this,"add","adding into "+this.g.name+" with value ",a,b)};
var Hd=function(a,b){var c=new W;try{var d=a.g["delete"](b)}catch(e){d=Ja+a.g.name+ma+S(b);X(c,R(e,d));return}d.onsuccess=function(){c.g()};d.onerror=function(e){var f=Ja+a.g.name+ma+S(b);X(c,hc(e.target,f))}};Ed.prototype.get=function(a){var b=new W;try{var c=this.g.get(a)}catch(e){return c="getting from "+this.g.name+ma+S(a),X(b,R(e,c)),b}c.onsuccess=function(e){b.g(e.target.result)};var d=this;c.onerror=function(e){var f="getting from "+d.g.name+ma+S(a);X(b,hc(e.target,f))};return b};
var Id=function(a,b){var c=new W;try{var d=a.g.getAll(void 0,void 0)}catch(e){return b+=la,X(c,R(e,b)),c}d.onsuccess=function(){c.g(d.result)};d.onerror=function(e){b+=la;X(c,hc(e.target,b))};return c};Ed.prototype.clear=function(){var a="clearing store "+this.g.name,b=new W;try{var c=this.g.clear()}catch(d){return X(b,R(d,a)),b}c.onsuccess=function(){b.g()};c.onerror=function(d){X(b,hc(d.target,a))};return b};
var Jd=function(a){this.h=a;this.g={}};P(Jd,kc);var Ld=[];Jd.prototype.A=function(a,b,c,d){Array.isArray(b)||(b&&(Ld[0]=b.toString()),b=Ld);for(var e=0;e<b.length;e++){var f=Sa(a,b[e],c||this.handleEvent,d||!1,this.h||this);if(!f)break;this.g[f.key]=f}return this};Jd.prototype.fa=function(a,b,c,d){return Md(this,a,b,c,d)};var Md=function(a,b,c,d,e,f){if(Array.isArray(c))for(var l=0;l<c.length;l++)Md(a,b,c[l],d,e,f);else{b=Cc(b,c,d||a.handleEvent,e,f||a.h||a);if(!b)return a;a.g[b.key]=b}return a};
Jd.prototype.T=function(a,b,c,d,e){if(Array.isArray(b))for(var f=0;f<b.length;f++)this.T(a,b[f],c,d,e);else c=c||this.handleEvent,d=N(d)?!!d.capture:!!d,e=e||this.h||this,c=Dc(c),d=!!d,b=rc(a)?a.I(b,c,d,e):a?(a=Fc(a))?a.I(b,c,d,e):null:null,b&&(Kc(b),delete this.g[b.key])};Jd.prototype.handleEvent=function(){throw Error("n");};
var Nd=function(a,b){U.call(this);this.g=a;this.j=b;this.i=new Jd(this);this.i.A(this.g,Aa,O(this.dispatchEvent,this,Aa));this.i.A(this.g,za,O(this.dispatchEvent,this,za));this.i.A(this.g,F,this.na)};P(Nd,U);x=Nd.prototype;x.na=function(a){a.target instanceof Wb?this.dispatchEvent({type:F,target:a.target}):this.dispatchEvent({type:F,target:hc(a.target,"in transaction")})};x.objectStore=function(a){try{return new Ed(this.g.objectStore(a))}catch(b){throw R(b,"getting object store "+a);}};
x.commit=function(a){if(this.g.commit||!a)try{this.g.commit()}catch(b){throw R(b,"cannot commit the transaction");}};x.wait=function(){var a=new W;Cc(this,Aa,O(a.g,a));var b=Cc(this,za,function(){Kc(c);X(a,new Wb(bc,"waiting for transaction to complete"))});var c=Cc(this,F,function(e){Kc(b);X(a,e.target)});var d=this.j;return yd(a,function(){return d})};x.abort=function(){this.g.abort()};
var Od=function(a){U.call(this);this.g=a;this.i=new Jd(this);this.i.A(this.g,za,O(this.dispatchEvent,this,za));this.i.A(this.g,F,this.l);this.i.A(this.g,"versionchange",this.o);this.i.A(this.g,"close",O(this.dispatchEvent,this,"close"))};P(Od,U);Od.prototype.j=!0;Od.prototype.l=function(a){a=(a=a.target)&&a.error;this.dispatchEvent({type:F,errorCode:a&&a.severity})};Od.prototype.o=function(a){this.dispatchEvent(new Pd(a.oldVersion,a.newVersion))};
Od.prototype.close=function(){this.j&&(this.g.close(),this.j=!1)};var Qd=function(a,b,c){try{a.g.createObjectStore(b,c)}catch(d){throw R(d,"creating object store "+b);}},Rd=function(a,b){try{var c=a.g.transaction(b,Ia);return new Nd(c,a)}catch(d){throw R(d,"creating transaction");}},Pd=function(a,b){T.call(this,"versionchange");this.oldVersion=a;this.newVersion=b};P(Pd,T);
var Sd=function(){void 0==Sb&&(Sb=E.indexedDB||E.mozIndexedDB||E.webkitIndexedDB||E.moz_indexedDB);return Sb},Td=function(a,b,c){var d=new W;b=b?Sd().open(a,b):Sd().open(a);b.onsuccess=function(e){e=new Od(e.target.result);d.g(e)};b.onerror=function(e){X(d,hc(e.target,"opening database "+a))};b.onupgradeneeded=function(e){if(c){var f=new Od(e.target.result);c(new Pd(e.oldVersion,e.newVersion),f,new Nd(e.target.transaction,f))}};b.onblocked=v();return d};
var Vd=function(a,b,c,d){c=void 0===c?{}:c;d=void 0===d?{}:d;this.url=a;this.i=void 0===b?0:b;this.h=c;this.g=d;this.keyPath=Ud()+"::"+a},Ud=ca("StoredCacheHitCounters"),Wd=function(a){if(a&&a.url&&typeof a.url===G&&typeof a.hits===Ha){var b;if(N(a.misses)){var c=a.misses;Object.keys(c).every(function(f){return typeof f===G&&typeof c[f]===Ha})&&(b=c)}var d;if(N(a.changes)){var e=a.changes;Object.keys(e).every(function(f){return typeof f===G&&typeof e[f]===Ha})&&(d=e)}return new Vd(a.url,a.hits,b,
d)}},Xd=function(a){var b={url:a.url,hits:a.i,keyPath:a.keyPath};a.h&&Object.keys(a.h).length&&(b.misses=a.h);a.g&&Object.keys(a.g).length&&(b.changes=a.g);return b},eb=function(a,b,c,d){this.scope=a;this.g=b;this.reason=c;this.time=d;this.keyPath=$a()+"::"+a},$a=ca("StoredCacheState"),bb=function(a){return{scope:a.scope,isEmpty:a.g,reason:a.reason,time:a.time.toDateString(),keyPath:a.keyPath}},ab=function(a){if(a&&typeof a.scope===G&&"boolean"===typeof a.isEmpty&&typeof a.reason===G&&Date.parse(a.time))return new eb(a.scope,
a.isEmpty,a.reason,new Date(a.time))},Za=function(a){this.g=a;this.h=Yd()},Zd=ca("gmail-sw-keyval-objects"),Yd=function(){return Promise.resolve(Td("gmail-sw-keyval",2,function(a,b){if((a=b.g.objectStoreNames)&&a.contains(Zd())){a=Zd();try{b.g.deleteObjectStore(a)}catch(c){throw R(c,"deleting object store "+a);}}Qd(b,Zd(),{keyPath:"keyPath"})}))};Za.prototype.get=function(a){var b=this;return $d(this,function(c){return c.get(b.g.O()+"::"+a)}).then(function(c){return b.g.parse(c)})};
var db=function(a,b,c){return $d(a,function(d){return new Promise(function(e,f){return zd(yd(d.get(a.g.O()+"::"+b),function(l){return e(Gd(d,a.g.ia(c(a.g.parse(l)))))}),function(l){return f(l)})})})},cb=function(a){return a.h.then(function(b){var c=Rd(b,[Zd()]).objectStore(Zd());return new Promise(function(d,e){return zd(yd(Id(c,"getting all from index "+c.g.name),function(f){d(f.filter(function(l){return l.keyPath&&l.keyPath.startsWith(a.g.O()+"::")}).map(function(l){Hd(c,l.keyPath);return a.g.parse(l)}).filter(function(l){return!!l}))}),
function(f){return e(f)})})})};Za.prototype.clear=function(){return $d(this,function(a){return a.clear()})};var $d=function(a,b){return a.h.then(function(c){c=Rd(c,[Zd()]);var d=c.objectStore(Zd());return Ta(c,b(d))})};
var Xa=function(){this.g=new Za({O:Ud,parse:Wd,ia:Xd})},ae=function(a,b){db(a.g,b,function(c){c=c||new Vd(b);c.i++;return c})},be=function(a,b,c){db(a.g,b,function(d){d=d||new Vd(b);d.h[c]?d.h[c]++:d.h[c]=1;return d})},Ya=function(a,b){db(a.g,b,function(c){c=c||new Vd(b);c.g.quota_exceeded?c.g.quota_exceeded++:c.g.quota_exceeded=1;return c})};Xa.prototype.get=function(a){return this.g.get(a)};
var nb=new Set(["auth","hl","zx","tab","ui","authuser","tz","pli","shva","ibxr",Ca,"e","features","jsmode","labs","traceDebugger","ddpk","ogbl","usp","sno"]);
var ce=RegExp("^(?:([^:/?#.]+):)?(?://(?:([^\\\\/?#]*)@)?([^\\\\/?#]*?)(?::([0-9]+))?(?=[\\\\/?#]|$))?([^?#]+)?(?:\\?([^#]*))?(?:#([\\s\\S]*))?$"),de=function(a,b){if(a){a=a.split("&");for(var c=0;c<a.length;c++){var d=a[c].indexOf("="),e=null;if(0<=d){var f=a[c].substring(0,d);e=a[c].substring(d+1)}else f=a[c];b(f,e?decodeURIComponent(e.replace(/\+/g," ")):"")}}},ee=function(a,b,c){if(Array.isArray(b))for(var d=0;d<b.length;d++)ee(a,String(b[d]),c);else null!=b&&c.push(a+(""===b?"":"="+encodeURIComponent(String(b))))};
var fe=function(a){this.i=this.o=this.j="";this.s=null;this.m=this.g="";this.l=!1;var b;a instanceof fe?(this.l=a.l,ge(this,a.j),this.o=a.o,this.i=a.i,he(this,a.s),this.g=a.g,ie(this,je(a.h)),this.m=a.m):a&&(b=String(a).match(ce))?(this.l=!1,ge(this,b[1]||"",!0),this.o=ke(b[2]||""),this.i=ke(b[3]||"",!0),he(this,b[4]),this.g=ke(b[5]||"",!0),ie(this,b[6]||"",!0),this.m=ke(b[7]||"")):(this.l=!1,this.h=new Y(null,this.l))};
fe.prototype.toString=function(){var a=[],b=this.j;b&&a.push(le(b,me,!0),":");var c=this.i;if(c||"file"==b)a.push("//"),(b=this.o)&&a.push(le(b,me,!0),"@"),a.push(encodeURIComponent(String(c)).replace(/%25([0-9a-fA-F]{2})/g,"%$1")),c=this.s,null!=c&&a.push(":",String(c));if(c=this.g)this.i&&"/"!=c.charAt(0)&&a.push("/"),a.push(le(c,"/"==c.charAt(0)?ne:oe,!0));(c=this.h.toString())&&a.push("?",c);(c=this.m)&&a.push("#",le(c,pe));return a.join("")};
fe.prototype.resolve=function(a){var b=new fe(this),c=!!a.j;c?ge(b,a.j):c=!!a.o;c?b.o=a.o:c=!!a.i;c?b.i=a.i:c=null!=a.s;var d=a.g;if(c)he(b,a.s);else if(c=!!a.g){if("/"!=d.charAt(0))if(this.i&&!this.g)d="/"+d;else{var e=b.g.lastIndexOf("/");-1!=e&&(d=b.g.slice(0,e+1)+d)}e=d;if(".."==e||"."==e)d="";else if(-1!=e.indexOf("./")||-1!=e.indexOf("/.")){d=0==e.lastIndexOf("/",0);e=e.split("/");for(var f=[],l=0;l<e.length;){var k=e[l++];"."==k?d&&l==e.length&&f.push(""):".."==k?((1<f.length||1==f.length&&
""!=f[0])&&f.pop(),d&&l==e.length&&f.push("")):(f.push(k),d=!0)}d=f.join("/")}else d=e}c?b.g=d:c=""!==a.h.toString();c?ie(b,je(a.h)):c=!!a.m;c&&(b.m=a.m);return b};
var ge=function(a,b,c){a.j=c?ke(b,!0):b;a.j&&(a.j=a.j.replace(/:$/,""))},he=function(a,b){if(b){b=Number(b);if(isNaN(b)||0>b)throw Error("o`"+b);a.s=b}else a.s=null},ie=function(a,b,c){b instanceof Y?(a.h=b,qe(a.h,a.l)):(c||(b=le(b,re)),a.h=new Y(b,a.l))},qb=function(a){return a instanceof fe?new fe(a):new fe(a)},ke=function(a,b){return a?b?decodeURI(a.replace(/%25/g,"%2525")):decodeURIComponent(a):""},le=function(a,b,c){return typeof a===G?(a=encodeURI(a).replace(b,se),c&&(a=a.replace(/%25([0-9a-fA-F]{2})/g,
"%$1")),a):null},se=function(a){a=a.charCodeAt(0);return"%"+(a>>4&15).toString(16)+(a&15).toString(16)},me=/[#\/\?@]/g,oe=/[#\?:]/g,ne=/[#\?]/g,re=/[#\?@]/g,pe=/#/g,Y=function(a,b){this.h=this.g=null;this.i=a||null;this.j=!!b},J=function(a){a.g||(a.g=new Map,a.h=0,a.i&&de(a.i,function(b,c){a.add(decodeURIComponent(b.replace(/\+/g," ")),c)}))};Y.prototype.add=function(a,b){J(this);this.i=null;a=te(this,a);var c=this.g.get(a);c||this.g.set(a,c=[]);c.push(b);this.h+=1;return this};
var sb=function(a,b){J(a);b=te(a,b);a.g.has(b)&&(a.i=null,a.h-=a.g.get(b).length,a.g.delete(b))};Y.prototype.clear=function(){this.g=this.i=null;this.h=0};var ue=function(a,b){J(a);b=te(a,b);return a.g.has(b)};Y.prototype.forEach=function(a,b){J(this);this.g.forEach(function(c,d){c.forEach(function(e){a.call(b,e,d,this)},this)},this)};var ve=function(a,b){J(a);var c=[];if(typeof b===G)ue(a,b)&&(c=c.concat(a.g.get(te(a,b))));else for(a=Array.from(a.g.values()),b=0;b<a.length;b++)c=c.concat(a[b]);return c};
Y.prototype.set=function(a,b){J(this);this.i=null;a=te(this,a);ue(this,a)&&(this.h-=this.g.get(a).length);this.g.set(a,[b]);this.h+=1;return this};Y.prototype.get=function(a,b){if(!a)return b;a=ve(this,a);return 0<a.length?String(a[0]):b};
Y.prototype.toString=function(){if(this.i)return this.i;if(!this.g)return"";for(var a=[],b=Array.from(this.g.keys()),c=0;c<b.length;c++){var d=b[c],e=encodeURIComponent(String(d));d=ve(this,d);for(var f=0;f<d.length;f++){var l=e;""!==d[f]&&(l+="="+encodeURIComponent(String(d[f])));a.push(l)}}return this.i=a.join("&")};
var je=function(a){var b=new Y;b.i=a.i;a.g&&(b.g=new Map(a.g),b.h=a.h);return b},te=function(a,b){b=String(b);a.j&&(b=b.toLowerCase());return b},qe=function(a,b){b&&!a.j&&(J(a),a.i=null,a.g.forEach(function(c,d){var e=d.toLowerCase();if(d!=e&&(sb(this,d),sb(this,e),0<c.length)){this.i=null;d=this.g;var f=d.set;e=te(this,e);var l=c.length;if(0<l){for(var k=Array(l),m=0;m<l;m++)k[m]=c[m];l=k}else l=[];f.call(d,e,l);this.h+=c.length}},a));a.j=b};
var ib=/^\/mail\/(ca\/)?(u\/\d+\/)?$/,jb=/\/mail(\/ca)?\/b\/[^\/]+\/u\/[^\/]+/,lb=/\/mail\/u\/[^\/]+\/d\/[^\/]+/,kb=/\/a\/[^\/]+\/b\/[^\/]+\/u\/[^\/]+/,rb=new Set(["zx","tab","pli","shva","ibxr",Ca,"ddpk","ogbl","usp","sno"]),ub=/^\/chat\/(u\/\d+\/)?$/,vb=/^\/mail\/(ca\/)?(u\/\d+\/)?chat\/$/;
var xe=function(){this.g=we.caches},ze=function(a,b){return ye(a,b).then(function(c){if(c){var d=new URL(b.url);if(d.searchParams){var e=d.searchParams.get("disp");d="att"==d.searchParams.get("view")&&("safe"==e||"attd"==e||"zip"==e||"inzip"==e)}else d=!1;return d?(c.headers.get(pa)||(d="attachment",(e=c.headers.get("fileNameForDownload"))&&(d+="; filename="+e),c.headers.append(pa,d)),c.headers.append("Content-Security-Policy","default-src none"),c.headers.get(wa)||c.headers.append(wa,"nosniff"),
Promise.resolve(c)):c}return fetch(b)})},ye=function(a,b){b=(new URL(b.url)).searchParams;var c=[];b.get("permmsgid")?c.push("permmsgid="+b.get("permmsgid")):b.get("th")&&c.push("th="+b.get("th"));c.push("attid="+b.get("attid"));b.get("realattid")&&c.push("realattid="+b.get("realattid"));return a.g.match(c.join("&"))};
var Ae=function(){this.g={};this.i="";this.h={}};Ae.prototype.toString=function(){var a=this.i+Be(this);var b=this.h;var c=[],d;for(d in b)ee(d,b[d],c);b=c.join("&");c="";""!=b&&(c="?"+b);return a+c};
var Be=function(a){var b=[],c=O(function(d){void 0!==this.g[d]&&b.push(d+"="+this.g[d])},a);"1"==K(a,"md")?(c("md"),c("k"),c("ck"),c("am"),c("rs"),c(Da)):(c("sdch"),c("k"),c("ck"),c("am"),c("rt"),"d"in a.g||(a.g.d="0"),c("d"),c("exm"),c("excm"),(a.g.excm||a.g.exm)&&b.push("ed=1"),c("im"),c("dg"),c("sm"),"1"==K(a,"br")&&c("br"),""!==Ce(a)&&c("wt"),c(Da),c("rs"),c("ee"),c("cb"),c("m"));return b.join("/")},K=function(a,b){return a.g[b]?a.g[b]:null},Kb=function(a){return(a=K(a,"exm"))?a.split(","):[]},
Jb=function(a){return(a=K(a,"excm"))?a.split(","):[]},De=function(a){return(a=K(a,"m"))?a.split(","):[]},Ce=function(a){switch(K(a,"wt")){case "0":return"0";case "1":return"1";case "2":return"2";default:return""}},Lb=function(a){var b=K(a,"ee");if(!b)return{};a={};b=y(b.split(";"));for(var c=b.next();!c.done;c=b.next()){var d=y(c.value.split(":"));c=d.next().value;d=d.next().value;a[c]={};d=y(d.split(","));for(var e=d.next();!e.done;e=d.next())a[c][e.value]=!0}return a},Fe=function(a){var b=void 0===
b?!0:b;var c=Ee(a),d=new Ae,e=c.match(ce)[5];Na(function(l){var k=e.match("/"+l+"=([^/]+)");k&&((k=k[1])?d.g[l]=k:delete d.g[l])});var f=-1!=a.indexOf("_/ss/")?"_/ss/":"_/js/";d.i=a.substr(0,a.indexOf(f)+f.length);if(!b)return d;(a=c.match(ce)[6]||null)&&de(a,function(l,k){d.h[l]=k});return d},Ge=function(a){a=(a=Ee(a).match(ce)[5]||null)?decodeURI(a):a;return null!==a&&!!a.match("(/_/js/)|(/_/ss/)")&&!!a.match("/k=")},Ee=function(a){return a.startsWith("https://uberproxy-pen-redirect.corp.google.com/uberproxy/pen?url=")?
a.substr(65):a},Ma={Ra:"k",Ba:"ck",Na:"m",Ha:"exm",Fa:"excm",za:"am",Qa:"rt",Ka:"d",Ga:"ed",Va:"sv",Ca:"deob",Aa:"cb",Ta:"rs",Sa:"sdch",La:"im",Da:"dg",Ea:"br",Xa:"wt",Ia:"ee",Ua:"sm",Ma:"md",Ja:Da};
var He=self;
var Ie=function(a,b){this.l=void 0===a?!0:a;this.ha=new Map;this.S=[];this.ea=!1;this.h="";this.j=/\/\* ?_(?:(GlobalPrefix_)|(CSS)|(JS)|(M:)|(GlobalSuffix_))|(?=(?:|\/(?:|\* ?(?:|_[A-Za-z]*)))$)/g;this.g=this.aa;this.N=this.i=!1;this.Y={};this.ga={};this.ba="";this.da=!1;this.V=this.W=this.R=this.Z=this.U=this.ca="";this.wa=void 0===b?!1:b},Je=function(a,b){var c=new Map,d=[];b=y(b.split("/"));for(var e=b.next();!e.done;e=b.next()){var f=y(e.value.split(":"));e=f.next().value;var l=f.next().value;
f=[];if(l){l=y(l.split(","));for(var k=l.next();!k.done;k=l.next())f.push(d[parseInt(k.value,36)])}c.set(e,f);d.push(e)}a.ha=c;a.S=d;a.ea=!0},Ke=function(a,b){for(a.h+=b;;){var c=a.j.exec(a.h);if(!c)break;b=y(c);b.next();var d=b.next().value,e=b.next().value,f=b.next().value,l=b.next().value,k=b.next().value;b=a.g;if(d)a.g=a.ua;else if(e)a.g=a.ta;else if(f)a.g=a.xa;else if(l)a.g=a.ya;else if(k)a.g=a.va;else break;c=c.index;d=a.h.slice(0,c);a.h=a.h.slice(c);a.j.lastIndex-=c;b.call(a,d)}},Le=function(a){var b=
a.g,c=a.h;a.g=a.aa;a.h="";b.call(a,c)};x=Ie.prototype;x.aa=v();x.ua=function(a){this.ba=a};x.ta=function(a){this.i=!0;this.Z=a};x.xa=function(a){this.i=!1;var b=/^(.*\n)([^(\n]+)(\(function\([^]*)/.exec(a);if(b){var c=y(b);c.next();b=c.next().value;var d=c.next().value;c=c.next().value;this.W=b;this.V=c;this.N=/^[A-Z_$][\w$]*(\.[A-Z_$][\w$]*)*$/i.test(d);this.N||(this.R=a)}else this.R=a};
x.ya=function(a){var b=/^\/\* ?_M:([\w\-*]+) ?\*\//.exec(a);null!==b&&(b=b[1],this.i?this.Y[b]=a:this.ga[b]=a,this.l&&(a=/_ModuleManager_initialize\)?\('([\w\-*,:\/]+)'/.exec(a),null!==a&&Je(this,a[1])))};x.va=function(a){this.N||(this.da=!0,this.ca=a);if(a=/^(.*\n\}\))([^;\n]*)(;[^]*)/.exec(a)){var b=y(a);b.next();a=b.next().value;b.next();b=b.next().value;this.U=a+b}};
var Me=function(a,b){if(!a.ok)return Promise.reject(Error("q"));if(!b&&!Ge(a.url))return Promise.reject(Error("r"));b=b||Fe(a.url);if("1"==K(b,"md"))return a.json().then(function(k){var m=new Ie(!1,!0);Je(m,k.moduleGraph);return m});a:switch(K(b,"dg")){case "0":var c="0";break a;case "2":c="2";break a;default:c="1"}var d=new Ie("1"===c&&0===Kb(b).length,!1);if(!a.body)return a.text().then(function(k){Ke(d,k);Le(d);return d});var e=new TextDecoder,f=a.body.getReader(),l=function(){return f.read().then(function(k){if(k=
k.value)return k=e.decode(k,{stream:!0}),Ke(d,k),l();Le(d);return d})};return l()};
var Ne=function(){this.rootModule=this.moduleGraph=this.callbackSuffix=this.suffix=this.callbackJsSectionPrefixFooter=this.callbackJsSectionPrefixHeader=this.jsSectionPrefix=this.cssSectionPrefix=this.prefix=null;this.storedModules=new Set;this.storedCssModules=new Set;this.lastUseMs=Date.now()},Oe=function(a){this.h=a;this.g=null},Qe=function(a,b,c,d){return(a.g||Pe(a)).then(function(e){e=e.transaction([Fa,Ba,Ka],Ia);for(var f=e.objectStore(Fa),l=e.objectStore(Ba),k=e.objectStore(Ka),m=y(c.js.keys()),
n=m.next();!n.done;n=m.next()){n=n.value;var p={};f.put((p.content=c.js.get(n),p),b+";"+n)}f=y(c.css.keys());for(n=f.next();!n.done;n=f.next())m=n.value,n={},l.put((n.content=c.css.get(m),n),b+";"+m);var w=k.get(b);w.onsuccess=function(){var t=[],u=[],z=w.result;if(z){t=y("jsSectionPrefix cssSectionPrefix callbackJsSectionPrefixHeader callbackJsSectionPrefixFooter suffix callbackSuffix".split(" "));for(u=t.next();!u.done;u=t.next())u=u.value,null==d[u]&&(d[u]=z[u]);t=z.storedModules;u=z.storedCssModules}d.storedModules=
new Set([].concat(M(t),M(c.js.keys())));d.storedCssModules=new Set([].concat(M(u),M(c.css.keys())));k.put(d,b)};return Bb(e)})},Re=function(a,b,c){var d,e=IDBKeyRange.bound(b,b+String.fromCharCode(60));return(new Promise(function(f,l){d=setTimeout(function(){f(null)},5E3);(a.g||Pe(a)).then(function(k){var m=k.transaction([Fa,Ba],"readonly");k=function(w,t,u){var z=[].concat(M(t)).sort(),A=0;w.openCursor(e).onsuccess=function(qa){if((qa=qa.target.result)&&qa){var Ub=qa.key.split(";")[1],Kd=z[A];Ub>
Kd||(Ub==Kd&&(u.set(Ub,qa.value.content),++A),t.length!=u.size&&A<z.length&&qa.continue(b+";"+z[A]))}}};var n=new Map,p=new Map;k(m.objectStore(Ba),c.css,p);k(m.objectStore(Fa),c.js,n);m.oncomplete=function(){c.js.length!=n.size||c.css.length!=p.size?f(null):f({js:n,css:p})};m.onerror=m.onabort=function(){l(m.error)}})})).finally(function(){d&&clearTimeout(d)})},Se=function(a,b){return(a.g||Pe(a)).then(function(c){c=c.transaction([Ka],"readonly").objectStore(Ka).get(b);return Ab(c)})};
Oe.prototype.clear=function(){return(this.g||Pe(this)).then(function(a){a=a.transaction([Fa,Ba,Ka],Ia);a.objectStore(Fa).clear();a.objectStore(Ba).clear();a.objectStore(Ka).clear();return Bb(a)})};var Pe=function(a){var b=He.indexedDB.open(a.h,2);b.onupgradeneeded=zb;b.onblocked=v();a.g=Ab(b);a.g.then(function(c){return Te(a,c)});return a.g},Te=function(a,b){b.onclose=function(){a.g=null};b.onversionchange=function(c){c.newVersion||(b.close(),a.g=null)}};
var Gb=/(_ModuleManager_initialize\)?\('[\w\-*,:\/]+'\s*,\s*\[)[\w'"*,\s]+(\]\s*\))/g,Ue=function(a){this.g=new Oe(a)},Xe=function(a,b,c,d){if(b){var e=b.storedModules;if(!b.prefix||!e)return null;for(var f=y(De(c)),l=f.next();!l.done;l=f.next())if(!e.has(l.value))return null}var k=Ve(c,b);return k?Promise.all([b||We(a,d),Re(a.g,d,{js:k.js,css:k.css})]).then(function(m){m=y(m);var n=m.next().value,p=m.next().value;m=n.prefix;if(!p||!m)return null;var w=n.cssSectionPrefix,t;if(t=K(c,"cb")){var u=n.callbackJsSectionPrefixHeader,
z=n.callbackJsSectionPrefixFooter;var A=n.callbackSuffix;if(!u||!z||!A)return null;t=[u,L(t),z];A=[A]}else{t=n.jsSectionPrefix;A=n.suffix;if(!t||!A)return null;t=[t];A=[A]}u=n.rootModule;n=Hb(p.js,k.js,u);p=Hb(p.css,k.css,u);return new Response(new Blob([m,w].concat(M(p),M(t),M(n),M(A))),void 0)}):null};Ue.prototype.clear=function(){return this.g.clear()};
var We=function(a,b){return Se(a.g,b).then(function(c){return c?c:new Ne})},Ye=function(a,b,c){var d=0;d=void 0===d?0:d;var e=Cb(b);return Promise.all([Me(c,b),We(a,e)]).then(function(f){var l=y(f);f=l.next().value;var k=l.next().value;k.lastUseMs=Date.now();l=f.wa;var m=new Map,n=new Map;if(l||f.ea)k.moduleGraph=f.ha,k.rootModule=f.S&&f.S[0];if(!l){k.prefix=L(f.ba);k.cssSectionPrefix=L(f.Z);k.jsSectionPrefix=f.N?null:L(f.R);k.suffix=f.da?L(f.ca):null;k.callbackJsSectionPrefixHeader=Eb(f.W);k.callbackJsSectionPrefixFooter=
Eb(f.V);k.callbackSuffix=Eb(f.U);l=f.ga;for(var p in l)p in k.storedModules||m.set(p,L(l[p]));if(K(b,"ck")){p=f.Y;for(var w in p)w in k.storedCssModules||n.set(w,L(p[w]));w=Mb(b,k.moduleGraph);for(var t in l)w.has(t)||n.has(t)||n.set(t,new Uint8Array(0))}}return new Promise(function(u,z){setTimeout(function(){Qe(a.g,e,{js:m,css:n},k).then(u,z)},d)})})},Ve=function(a,b){if("1"==K(a,"d")){if(!b)return null;var c=b.moduleGraph,d=b.rootModule;if(c&&d){var e=Ib(De(a),c,Lb(a));if(e){var f="1"==K(a,"ed")?
new Set(Ib(Kb(a),c,Lb(a))):new Set(Kb(a));c=Mb(a,c);b=[];var l=[];"1"==K(a,"d")&&0===f.size&&e[0]!==d&&e.unshift(d);d=y(e);for(var k=d.next();!k.done;k=d.next())k=k.value,f.has(k)||b.push(k);if(null!=K(a,"ck"))for(a=y(e),k=a.next();!k.done;k=a.next())e=k.value,c.has(e)||l.push(e);a={js:b,css:l}}else a=null}else a=null;return a}return{js:De(a),css:null!=K(a,"ck")?De(a):[]}},Db=null,Fb=null;
var bf=function(){var a=we.caches,b=Ze($e),c=af;this.h=a;this.l=b;this.g=c;this.i=void 0;this.m="gmail-sw-modules-"+c},df=function(a,b){var c=(new Date).getTime();return a.h.match(tb(b.url)).then(function(d){return cf(a,d,b,c)})},cf=function(a,b,c,d){if(b){var e="unknown",f=!1,l=new URL(b.url);hb(l,a.g)?yb(b)?f=!0:e=Ea:gb(l)?xb(d,c,b)?f=!0:e=Ea:e="match_bad_url";return f?{v:!0,response:b}:{v:!1,reason:Promise.resolve(e)}}b=new URL(c.url);return hb(b,a.g)?{v:!1,reason:a.h.match(tb(c.url),{ignoreSearch:!0}).then(function(k){return k?
"no_match_changed_query":Ga})}:{v:!1,reason:Promise.resolve("unknown")}},ff=function(a,b){var c=fb(new URL(b.url),a.g);return c&&"js"==c.type?ef(a,b).catch(function(){return{v:!1,reason:Promise.resolve("module_set_cache_error")}}):Promise.resolve({v:!1,reason:Promise.resolve(Ga)})},gf=function(a,b,c){a.h.open("sw-"+a.g).then(function(d){d.put(tb(b.url),c)}).catch(a.j.bind(a)).then(function(){return Va(a.g,"fetch_new_app_shell",!1)})},ef=function(a,b){var c=Fe(b.url),d=Cb(c),e=hf(a);return We(e,d).then(function(f){return(f=
Xe(e,f,c,d))?f.then(function(l){return l?{v:!0,response:l}:{v:!1,reason:Promise.resolve(Ga)}}):{v:!1,reason:Promise.resolve(Ga)}})},kf=function(a,b,c){var d=fb(new URL(b.url),a.g);d?jf(a,d,b,c).then(function(){if("js"==d.type&&a.l){var e=Fe(b.url);e=Ye(hf(a),e,c)}else e=Promise.resolve();return e}):Promise.resolve()},jf=function(a,b,c,d){return a.h.open(b.name).then(function(e){return e.put(tb(c.url),d.clone())}).then(v()).catch(a.j.bind(a)).then(v())},hf=function(a){a.i||(a.i=new Ue(a.m));return a.i};
bf.prototype.j=function(a){return this.l?Promise.resolve(0):a instanceof DOMException?Wa():Promise.resolve(0)};
var Ze=function(a){return!!a.g&&"1"==a.g.get("offline")&&"1"==a.g.get("offline_allowed")};
var lf=new Set("a b it m m_i spit l sps t".split(" ")),of=function(a,b,c){if(!b.request||!b.request.url)throw Error("u");return c&&("only-if-cached"===b.request.cache?"same-origin"!==b.request.mode:1)?mf(a,b.request).then(function(d){return d?d:nf(a,b.request)},function(){return nf(a,b.request)}):nf(a,b.request)},mf=function(a,b){var c=new URL(b.url);return df(a.g,b).then(function(d){ob(qb(c))&&(a.i.g=[],pf(a.i,b.url));if(d.v)return d=d.response,b.headers.get(ya)||(ae(a.j,b.url),a.h.g.set(b.url,1)),
d;b.headers.get(ya)||d.reason.then(function(e){be(a.j,b.url,e);a.h.g.set(b.url,0)});return Ze(a.l)?ff(a.g,b).then(function(e){return e.v?e.response:null}):null})},nf=function(a,b){return fetch(b).then(function(c){a:{var d=b.url;if(Ge(b.url)){d=De(Fe(d));d=y(d);for(var e=d.next();!e.done;e=d.next())if(lf.has(e.value)){d=!0;break a}}d=!1}if(!d){d=a.g;e=c.clone();var f=new URL(b.url),l=new URL(e.url),k=new URL(e.url);if(hb(f,d.g)&&hb(k,d.g)&&200==e.status&&e.headers.get(xa))gf(d,b,e);else{if(f=gb(f)&&
gb(l))if(200!=e.status)f=!1;else if(k=e.headers.get(na)){f=!1;l=!0;k=y(k.split(","));for(var m=k.next();!m.done;m=k.next())if(m=m.value.trim(),"public"==m&&(f=!0),"no-store"==m||"no-cache"==m||"private"==m)l=!1;f=l&&f}else f=!1;f?kf(d,b,e):Promise.resolve()}}return c},function(c){throw c;})};
var qf=function(a,b){return a.g.has(b)?{sa:a.g.get(b)}:{sa:-1}};
var sf=function(){this.g=rf()},tf=ca("locks-object-store"),rf=function(){return Promise.resolve(Td("gmail-sw-locks",1,function(a,b){Qd(b,tf(),{keyPath:"lockId"})})).catch(v())},uf=function(a,b){return new Promise(function(c,d){return zd(yd(a.objectStore(tf()).get(b),function(e){return c(e)}),function(e){return d(e)})})},vf=function(a,b,c){var d={lockId:b,clientId:c};return new Promise(function(e,f){return zd(yd(Gd(a.objectStore(tf()),d),function(){return e()}),function(l){return f(l)})})};
sf.prototype.clear=function(){return this.g.then(function(a){return Rd(a,[tf()]).objectStore(tf()).clear()})};
var wf=function(){this.g=new sf},yf=function(a,b){if(b.ports&&b.ports.length&&b.ports[0]){var c=b.ports[0];if(b.data.params&&b.data.params.lockId&&b.source&&b.source.id){var d=b.data.params.fullResult;xf(a,b.data.params.lockId,b.source.id).then(function(e){d?c.postMessage({resultCode:e}):c.postMessage(1==e);return e},function(e){c.postMessage({error:e})})}else c.postMessage({error:"Got a message event with incomplete request, ignoring."}),Promise.resolve(0)}else Promise.resolve(0)},xf=function(a,
b,c){return a.g.g.then(function(d){if(!d)throw Error("v");var e=Rd(d,[tf()]);return uf(e,b).then(function(f){return f?zf(f,c,d):vf(e,b,c).then(function(){return Ta(e,1)})})})},zf=function(a,b,c){return self.clients.get(a.clientId).then(function(d){if(d)return d.id==b?Promise.resolve(1):Promise.resolve(2);var e=Rd(c,[tf()]);return uf(e,a.lockId).then(function(f){return f&&a.clientId!=f.clientId?Promise.resolve(2):vf(e,a.lockId,b).then(function(){return Ta(e,1)})})})};
var Af=function(){this.g=we.caches},Bf=function(a,b){return a.g.match(b).then(function(c){return c?c:fetch(b).then(function(d){return d&&"opaque"!=d.type&&!d.ok?d.clone().text().then(function(){return d}):d}).catch(v())})};
var pf=function(a,b){a.g.push({ab:"AppShellLookUp",endTime:(new Date).getTime(),Za:void 0===b?null:b})};
var Ff=function(){var a=$e,b=Cf,c=Df,d=Ef,e=new xe,f=new Af;this.g=we;this.l=a;this.h=b;this.m=c;this.H=new URL(this.g.registration.scope);this.C=mb(this.H);this.i=d;this.s=e;this.j=f};Ff.prototype.D=function(a){this.g.registration.navigationPreload&&a.waitUntil(this.g.registration.navigationPreload.disable())};Ff.prototype.G=function(a){a.waitUntil(this.g.skipWaiting().then(ca(null)))};
Ff.prototype.F=function(a){var b=new URL(a.request.url),c;if(c=!(b.searchParams.has("sw")&&"2"==b.searchParams.get("sw")))c=!(!this.C&&(mb(b)||a.request.referrer&&mb(new URL(a.request.referrer))));if(c){if(Ze(this.l)){if(b.searchParams&&b.searchParams.has("th")&&b.searchParams.has("attid")&&(!b.searchParams.has("view")||"snatt"!=b.searchParams.get("view"))){a.respondWith(ze(this.s,a.request));return}if(b.hostname.endsWith(".gstatic.com")&&(b.pathname.endsWith(".png")||b.pathname.endsWith(".gif")||
b.pathname.endsWith(".cur"))){a.respondWith(Bf(this.j,a.request));return}}b.hostname.endsWith(".gstatic.com")&&(b.pathname.includes("/noconnection/")||b.pathname.includes("/rfr/logo_chat_default")||b.pathname.includes("/rfr/logo_chat_dark")||b.pathname.includes("/rfr/logo_gmail_lockup_default")||b.pathname.includes("/rfr/logo_gmail_lockup_dark"))?a.respondWith(Bf(this.j,a.request)):(b=gb(b)||hb(b,this.i.m)&&!(b.searchParams&&"0"==b.searchParams.get("sw_cache")))&&a.respondWith(of(this.i,a,b))}};
Ff.prototype.o=function(a){if(a.ports&&a.ports.length&&a.ports[0]){var b=a.ports[0],c=a.data.command;switch(c){case "get_client_id":b.postMessage(a.source&&a.source.id||"null");break;case "get_offline_lock":yf(new wf,a);break;case "get_trace_sections":a=this.h.g;this.h.g=[];b.postMessage(a);break;case "get_network_record":a=qf(this.m,a.data.params.requestUrl);b.postMessage(a);break;case "get_compression_info":var d=a.data.params.url;(a=(this.g.performance&&this.g.performance.getEntries?this.g.performance.getEntries():
[]).find(function(e){return e.name==d}))&&b.postMessage({encodedBodySize:a.encodedBodySize||-1,decodedBodySize:a.decodedBodySize||-1,transferSize:a.transferSize||-1});b.postMessage({});break;case "clear_resource_timing_buffer":this.g.performance&&this.g.performance.clearResourceTimings&&this.g.performance.clearResourceTimings();b.postMessage({});break;default:b.postMessage({error:"Got an unsupported command: "+c})}}};
var we=self,$e=new function(){this.g=(new URL(E.location.toString())).searchParams},Cf=new function(){this.g=[]},Df=new function(){this.g=new Map},af=(new URL(we.registration.scope)).pathname,Ef=new function(){var a=new bf,b=new Xa,c=Cf,d=Df,e=$e,f=af;this.g=a;this.j=b;this.l=e;this.m=f;this.i=c;this.h=d},Z=new Ff;Z.g.addEventListener("install",Z.G.bind(Z),!1);Z.g.addEventListener(aa,Z.D.bind(Z),!1);Z.g.addEventListener("fetch",Z.F.bind(Z),!1);Z.g.addEventListener("message",Z.o.bind(Z),!1);

}catch(e){_DumpException(e)}
// Google Inc.
